### PR TITLE
1.18.2 Rubidium support

### PR DESCRIPTION
**Pull request by DeshiDesu**
image
Compiled and fully tested.

If you want to compile the PR, follow the tutorial in this video: https://www.youtube.com/watch?v=WnTx3GguYi8&t=83s

### CODE REVIEW

**Comment by DeshiDesu** [comment]
Compatible with Rubidium mc1.18.2-0.5.6 and Forge 40.2.10

**Comment by DeshiDesu** [comment]
fixes https://github.com/bottomtextdanny/Effective-Forge-/issues/23 https://github.com/bottomtextdanny/Effective-Forge-/issues/25

**Comment by vgrynch** [comment]
Can this be fixed for 1.19.2 as well? The same there

**Comment by DeshiDesu** [comment]
> Can this be fixed for 1.19.2 as well? The same there

there is already a fix https://github.com/bottomtextdanny/Effective-Forge-/pull/29

**Comment by Mystic-Ervo** [comment]
I just tried to build it with Gradle and I got a `General error during conversion: Unsupported class file major version 64`
Is there a problem with Java 17?

**Comment by BrangGit** [comment]
Hi, very cool to see it working with Rubidium, do you plan on releasing it in a next update ?

**Pull request closed without merging**
